services:
  db:
    container_name: db
    image: postgres:15
    restart: unless-stopped
    env_file: .env
    ports:
      - "5433:5432"
    networks:
      - payment_bot_net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U db_bot_user -d db_bot_prod" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:6.0
    user: redis
    restart: unless-stopped
    networks:
      - payment_bot_net
    volumes:
      - redis_data:/data
    command: redis-server
      --dir /data
      --dbfilename dump.rdb
      --appendonly yes
      --appendfilename appendonly.aof
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    container_name: web
    build: .
    restart: unless-stopped
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - cdn_volume_data:/app/cdn/
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - payment_bot_net
    env_file: .env

  nginx:
    container_name: nginx
    image: nginx:1.25
    restart: always
    ports:
      - "127.0.0.1:1040:1040"
    networks:
      - payment_bot_net
    volumes:
      - cdn_volume:/app/cdn/
      - ./nginx/nginx.bot.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  postgres_data:
  redis_data:
  cdn_volume:

networks:
  payment_bot_net:
    driver: bridge
